name: Navdeep Test

on:
  push:
    branches:
      - develop

jobs:
  e2e-tests:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16' 

      - name: Install dependencies
        run: npm install

      - name: Run E2E tests
        run: npm run e2e  

